name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Global build step: run the global build command from the repo root.
      - name: Install Dependencies and Build Project
        run: |
          npm install
          npm run build
          echo "Build complete. Listing contents of the dist folder:"
          ls -R dist/

      # Deploy the register frontend
      - name: Deploy Register Frontend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/register/*"
          target: "/home/tezzeraktmedia-inspire/htdocs/inspire.tezzeraktmedia.space/"
          strip_components: 1
          rm: true

      # Deploy the backend
      - name: Deploy Backend to VPS (Exclude upload directories)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "Backend/*"
          target: "/home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/"
          strip_components: 1
          rsync_opts: "--exclude=uploads/ --exclude=socialIcons/ --exclude=galleryuploads/"

      - name: Ensure Upload Folders Exist on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Ensuring upload directories exist..."
            mkdir -p /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/uploads
            mkdir -p /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/socialIcons
            mkdir -p /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/galleryuploads
            chmod -R 755 /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/uploads
            chmod -R 755 /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/socialIcons
            chmod -R 755 /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/galleryuploads
            echo "Upload directories ensured on VPS."

      - name: Install Dependencies and Restart Backend Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Installing backend dependencies..."
            cd /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend
            npm install --production
            echo "Restarting backend service..."
            pm2 restart inspire-api

      # Deploy the admin frontend
      - name: Deploy Admin Frontend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/admin/*"
          target: "/home/tezzeraktmedia-admin-inspire/htdocs/admin.inspire.tezzeraktmedia.space/"
          strip_components: 1
          rm: true

      # Deploy the user interface
      - name: Deploy User Frontend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/user/*"
          target: "/home/tezzeraktmedia-user-inspire/htdocs/user.inspire.tezzeraktmedia.space/"
          strip_components: 1
          rm: true
