name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies and Build Frontend
        run: |
          cd Frontend/registerFrontEnd
          npm install
          npm run build

      - name: Debug Repository Files
        run: |
          echo "Listing files in Frontend/registerFrontEnd/dist/"
          ls -R Frontend/registerFrontEnd/dist/

      - name: Deploy Frontend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "Frontend/registerFrontEnd/dist/*"
          target: "/home/tezzeraktmedia-inspire/htdocs/inspire.tezzeraktmedia.space/"
          strip_components: 3
          rm: true

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy Backend to VPS (Exclude upload directories)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "Backend/*"
          target: "/home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/"
          strip_components: 1
          rsync_opts: "--exclude=uploads/ --exclude=socialIcons/ --exclude=galleryuploads/"

      - name: Ensure Upload Folders Exist on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Ensuring upload directories exist..."
            mkdir -p /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/uploads
            mkdir -p /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/socialIcons
            mkdir -p /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/galleryuploads
            chmod -R 755 /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/uploads
            chmod -R 755 /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/socialIcons
            chmod -R 755 /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend/galleryuploads
            echo "All upload directories ensured on VPS."

      - name: Install Dependencies and Restart Backend Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Installing dependencies..."
            cd /home/tezzeraktmedia-api-inspire/htdocs/api.inspire.tezzeraktmedia.space/backend
            npm install --production
            echo "Restarting backend service..."
            pm2 restart inspire-api

  deploy-admin:
    name: Deploy Admin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies and Build Admin Frontend
        run: |
          cd Frontend/adminFrontEnd
          npm install
          npm run build

      - name: Debug Admin Files
        run: |
          echo "Listing files in Frontend/adminFrontEnd/dist/"
          ls -R Frontend/adminFrontEnd/dist/

      - name: Deploy Admin to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "Frontend/adminFrontEnd/dist/*"
          target: "/home/tezzeraktmedia-admin-inspire/htdocs/admin.inspire.tezzeraktmedia.space/"
          strip_components: 3
          rm: true

  deploy-user:
    name: Deploy User Interface
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies and Build User Frontend
        run: |
          cd Frontend/userFrontEnd
          npm install
          npm run build

      - name: Debug User Files
        run: |
          echo "Listing files in Frontend/userFrontEnd/dist/"
          ls -R Frontend/userFrontEnd/dist/

      - name: Deploy User Interface to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "Frontend/userFrontEnd/dist/*"
          target: "/home/tezzeraktmedia-user-inspire/htdocs/user.inspire.tezzeraktmedia.space/"
          strip_components: 3
          rm: true
